project_id = "dcjurgffzjpjxqpmqtkd"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.upgrade-subscription]
verify_jwt = false

[functions.get-invoices]
verify_jwt = false

[functions.test-prerender]
verify_jwt = false

[functions.check-dns]
verify_jwt = false

[functions.log-crawl]
verify_jwt = false

[functions.landing-test]
verify_jwt = false

[functions.translate]
verify_jwt = false

[functions.sync-translations]
verify_jwt = false

[functions.prerender-proxy]
verify_jwt = false
